#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This program must be run as root" 
   exit 1

fi
    function print_usage {
        echo "Program usage:" >&2
        echo "[-b] : show blocked ip" >&2
        echo "[-c] : Configure the IP and Ports" >&2
        echo "[-r] : Run the IDS" >&2
        echo "[-e] : Kill all running IDS processes" >&2
        echo "[-u] : Unblock IP" >&2
        echo "[-h] : Help Menu" >&2
        exit 1
    }
    if [ $# -eq 0 ]
    then
        print_usage
    fi
        while getopts 'bcrehu' OPTION; do
        case "$OPTION" in
            b)
                sudo cat ipdata
                ;;
            c)
                sudo python3 input_config.py
                ;;
            r)
                sudo python3 raw_sniffer_demo.py &
                sudo python3 baru_monitor.py &
                ;;
            e)
                sudo pkill -9 -f raw_sniffer_demo.py ||
                sudo pkill -9 -f baru_monitor.py
                ;;
            h)
                print_usage
                ;;
            u)
                sudo python3 unblock.py $2
                ;;
            ?)
                print_usage
                ;;
            esac
        done
        shift "$(($OPTIND -1))"